project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: ims.csl

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)

execute:
  freeze: auto

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

jupyter: ml25notes

format:
  bookup-html:
      toc: true
      toc-depth: 3
  # html:
  #   theme: 
  #     - lumen
  #   code-block-bg: true
  #   code-block-border-left: true #"#31BAE9"
  #   code-line-numbers: true
  #   highlight-style: atom-one
  # pdf:
  #   documentclass: scrreprt

book:
  title: "Machine Learning {{< var info.date >}}"
  subtitle: "Lecture notes for {{< var info.date >}} at Arkansas Tech University"
  author: "Xinli Xiao"
  date: last-modified
  # downloads: [pdf]
  # crossref:
  #   app-prefix: Appendix

  chapters: 
    - index.qmd
    - contents/1/intro.qmd
    - contents/2/intro.qmd
    - contents/3/intro.qmd
    - contents/4/intro.qmd
    - contents/5/intro.qmd
    # - contents/6/intro.qmd
    # - contents/7/intro.qmd
  #   - part: "Part II: R"
  #     chapters:
  #       - contents/7/07-.qmd
  #       - contents/8/08-.qmd
  #   - contents/references.qmd
  appendices:
    # - contents/app/concepts.qmd
    # - contents/app/path.qmd
    - contents/app/setup.qmd
    # - contents/app/virtenv.qmd
  #   - contents/app/r.qmd
  sidebar:
    style: "docked"
    pinned: true
    align: center
    border: true
    search: true
    collapse-level: 1
  navbar:
    subtitle: "{{< var info.date >}}"
    # left:
    #     - text: "Introduction"
    #     - href: contents/1/intro.qmd

  page-navigation: true


    



